### ISSUE TITLE
会社: DAIMYO がないので、DAIMYOの場合の動作が確認できないので、会社: DAIMYOとそれに所属するユーザーを作りたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3579]
nameが`DAIMYO Engineer College`のデータが欲しい。

**Comment by machida** [comment]
`/db/fixtures/companies.yml`

の

```
company4:
  name: "SankakuSankaku Inc"
  description: "△△株式会社"
  website: "http://example.com/loriann"
  created_at: 2000-01-01 00:00:04
```

の社名を `DAIMYO Engineer College` にする。
description にDAIMYOの動作確認で使う、などの説明を書いておく。
