### ISSUE TITLE
rubocopのバージョンアップで出力されるようになったスタイル違反を修正して欲しい

### ISSUE THREAD

**Issue by ymmtd0x0b** [fjordllc/bootcamp#6495]
## 概要

https://github.com/fjordllc/bootcamp/pull/6370#issuecomment-1507213465 にて警告対象の１つである『否定形のif文 ( if !wip? のような書き方 ) 』を許容する方針変更があり、rubocop-fjord をバージョンアップして頂きました ([rubocop-fjordの修正コミット](https://github.com/fjordllc/rubocop-fjord/commit/1714632d46a8f376512ffac24976573d94a0ac93))

その後、開発環境の rubocop-fjord を`0.2.0`から`0.3.0`へバージョンアップして rubocop を実行したところ、今回の変更とは別ルールのスタイル違反が出力されるようになりました

違反しているスタイルと該当ファイルを`.robocop_todo.yml`に退避させ rubocop のチェック対象から除外していますので、対応をお願いしたいです

## 期待される振る舞い

`robocop_todo.yml`を削除した状態で rubocop を実行してもスタイル違反が出力されなくなる

## 違反スタイルと対象ファイル

<details>
<summary>.rubocop_todo.ymlの内容</summary>

```yml
# This configuration was generated by
# `rubocop --auto-gen-config --auto-gen-only-exclude --exclude-limit 1000`
# on 2023-07-02 06:34:03 UTC using RuboCop version 1.37.1.
# The point is for the user to remove these configuration records
# one by one as the offenses are removed from the code base.
# Note that changes in the inspected code, or installation of new
# versions of RuboCop, may require this file to be generated again.

# Offense count: 386
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle, EnforcedShorthandSyntax, UseHashRocketsWithSymbolValues, PreferHashRocketsForNonAlnumEndingSymbols.
# SupportedStyles: ruby19, hash_rockets, no_mixed_keys, ruby19_no_mixed_keys
# SupportedShorthandSyntax: always, never, either, consistent
Style/HashSyntax:
  Exclude:
    - 'app/controllers/admin/campaigns_controller.rb'
    - 'app/controllers/announcements_controller.rb'
    - 'app/controllers/api/admin/count_controller.rb'
    - 'app/controllers/api/bookmarks_controller.rb'
    - 'app/controllers/api/checks_controller.rb'
    - 'app/controllers/api/followings_controller.rb'
    - 'app/controllers/api/products/unchecked_controller.rb'
    - 'app/controllers/api/session_controller.rb'
    - 'app/controllers/api/watches/toggle_controller.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/notifications/read_by_category_controller.rb'
    - 'app/controllers/notifications_controller.rb'
    - 'app/controllers/products_controller.rb'
    - 'app/controllers/user_sessions_controller.rb'
    - 'app/helpers/meta_tags_helper.rb'
    - 'app/helpers/page_tab_helper.rb'
    - 'app/helpers/reactions_helper.rb'
    - 'app/jobs/ai_answer_create_job.rb'
    - 'app/mailers/activity_mailer.rb'
    - 'app/mailers/notification_mailer.rb'
    - 'app/models/announcement_notifier.rb'
    - 'app/models/answer.rb'
    - 'app/models/answer_notifier.rb'
    - 'app/models/card.rb'
    - 'app/models/chat_notifier.rb'
    - 'app/models/check_callbacks.rb'
    - 'app/models/comment.rb'
    - 'app/models/comment/after_create_callback.rb'
    - 'app/models/concerns/mentioner.rb'
    - 'app/models/concerns/reactionable.rb'
    - 'app/models/concerns/searchable.rb'
    - 'app/models/correct_answer_notifier.rb'
    - 'app/models/discord/server.rb'
    - 'app/models/event.rb'
    - 'app/models/first_report_notifier.rb'
    - 'app/models/grass.rb'
    - 'app/models/learning.rb'
    - 'app/models/notification.rb'
    - 'app/models/notification_facade.rb'
    - 'app/models/notifier_to_watching_user.rb'
    - 'app/models/page_notifier.rb'
    - 'app/models/practice.rb'
    - 'app/models/product.rb'
    - 'app/models/product_callbacks.rb'
    - 'app/models/product_notifier_for_colleague.rb'
    - 'app/models/product_notifier_for_practice_watcher.rb'
    - 'app/models/question_callbacks.rb'
    - 'app/models/reaction.rb'
    - 'app/models/regular_event/participants_creator.rb'
    - 'app/models/regular_event/participants_watcher.rb'
    - 'app/models/regular_event_update_notifier.rb'
    - 'app/models/report.rb'
    - 'app/models/report_notifier.rb'
    - 'app/models/searcher.rb'
    - 'app/models/subscription.rb'
    - 'app/models/unfinished_data_destroyer.rb'
    - 'app/models/user.rb'
    - 'app/notifiers/activity_notifier.rb'
    - 'app/notifiers/discord_notifier.rb'
    - 'lib/bootcamp/setup.rb'
    - 'test/deliveries/activity_delivery_test.rb'
    - 'test/mailers/activity_mailer_test.rb'
    - 'test/mailers/notification_mailer_test.rb'
    - 'test/mailers/previews/activity_mailer_preview.rb'
    - 'test/mailers/previews/notification_mailer_preview.rb'
    - 'test/models/answer_test.rb'
    - 'test/models/bookmark_test.rb'
    - 'test/models/category_test.rb'
    - 'test/models/discord/times_channel_test.rb'
    - 'test/models/event_test.rb'
    - 'test/models/product_test.rb'
    - 'test/models/question_test.rb'
    - 'test/models/regular_event/participants_creator.rb'
    - 'test/models/regular_event/participants_watcher_test.rb'
    - 'test/models/regular_event_test.rb'
    - 'test/models/user_test.rb'
    - 'test/notifiers/discord_notifier_test.rb'
    - 'test/supports/api_helper.rb'
    - 'test/supports/tag_helper.rb'
    - 'test/system/announcements_test.rb'
    - 'test/system/company/products_test.rb'
    - 'test/system/current_user/products_test.rb'
    - 'test/system/notification/products_test.rb'
    - 'test/system/notification/questions_test.rb'
    - 'test/system/notification/signed_up_test.rb'
    - 'test/system/product/self_assigned_test.rb'
    - 'test/system/product/unchecked_test.rb'
    - 'test/system/sign_up_test.rb'
    - 'test/system/user/products_test.rb'
    - 'test/test_helper.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Style/RedundantFreeze:
  Exclude:
    - 'app/models/link_checker/extractor.rb'
```

</details>

## 注意
`.rubocop_todo.yml`に除外した内容が記載されていますが、これは Issue 作成時の実行結果になります。Issue に取り組む際は事前に`rubocop --auto-gen-config --auto-gen-only-exclude --exclude-limit 1000`を実行して `.rubocop_todo.yml`を再生成し、最新の状態を把握した方が良いと思われます

## 関連Issue

Ref: #6496
