### ISSUE TITLE
通知のユーザーアイコンにroleを付けたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#6523]
<img width="260" alt="貼り付けた画像_2023_05_15_13_52" src="https://github.com/fjordllc/bootcamp/assets/168265/72b31609-acc0-49ed-9c17-6f64001587cc">

現状、このユーザーアイコンに role のマークが付いていない（色がついた枠）。
ユーザーアイコンのimgタグに、

```html
<span class="a-user-role {role 例: is-admin}">
    <img>
</span>
```

のように、span タグで囲う。

デザインが崩れたら machida が対応します。

**Comment by syo-tokeshi** [comment]
@machida 
お疲れ様です。

こちら、通知がきたユーザーに対するアイコンを付与する、ということですが、

1. ユーザーのロール(役割)の概念は、こちらのリストだけで良いか
[リスト]
https://github.com/fjordllc/bootcamp/blob/b81c5238270161c6ec21af4566996c6e3beed235/app/models/user.rb#L271
```
      admin: 管理者,
      mentor: メンター,
      adviser: アドバイザー,
      trainee: 研修生,
      hibernated_at: 休会者,
      graduated_on: 卒業者
```

2. 上記で挙げたリストのユーザーのロールを、このような感じで`span`タグの中で、クラスとして付与してあげれば良い
[例：roleがadminユーザーの場合]
```css
<span class="a-user-role {role : is-admin}">
    <img>
</span>
````
[例：roleがtraineeユーザーの場合]
```css
<span class="a-user-role {role : is-trainee}">
    <img>
</span>
````
