### ISSUE TITLE
slim-lintのルールを適用する1

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#7247]
slim-lintの指摘するルールの内、多くのルールを除外する設定にしている。（下記）
https://github.com/fjordllc/bootcamp/blob/00faadedb1027f1c5c6b212f1d758695997b7306/config/slim_lint.yml#L9-L42

このIssueでは1つのルールを有効化し、指摘されるviewファイルをルールに沿うように修正してください。

1Issueにつき1ルールとします。

また、ルールによっては有効化することが現実的で無いものも存在するかもしれないのでその場合は、どういうルールなのかを調べて、@komagata , @machida に連絡し、そのルールをこのプロジェクトに適用するのか議論してください。

実際には適用しないとしても、調査の作業を持ってIssueは完了とします。

**Comment by kyokucho1989** [comment]
お疲れ様です。私も同じ種類のIssueを担当にすることにしました。
有効化するルールが重複しないようにあらかじめ決めておいた方がいいと思います。

また、以下のルールはコメントアウトしても指摘されるviewファイルがありませんでした。
私はこの中から `Layout/MultilineMethodCallBraceLayout` を有効化しようと思います。

`config/slim_lint.yml`
```yml
exclude:
  - 'app/views/style_guide/**/*.slim'

linters:
  LineLength:
    max: 250
  RuboCop:
    enabled: true
    ignored_cops:
      # - Layout/ArrayAlignment
      # - Layout/BlockAlignment
      # - Layout/EndAlignment
      # - Layout/FirstArrayElementIndentation
      # - Layout/FirstParameterIndentation
      # - Layout/InitialIndentation
      # - Layout/MultilineArrayBraceLayout
      # - Layout/MultilineAssignmentLayout
      # - Layout/MultilineHashBraceLayout
      # - Layout/MultilineMethodCallBraceLayout
```
