### ISSUE TITLE
user_decoratorのrubocopの指摘に対応できるようにする

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#8808]
現状、rubocopの指摘を下記のように設定ファイルで除外することで回避している。

```yaml
Metrics/ModuleLength:
  Exclude:
    - app/decorators/user_decorator.rb
``` 

この設定を削除し、`Metrics/ModuleLength`の指摘が出ないように該当のコードをリファクタリングする。
